//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lemon_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Common_Fruit_Veg_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Common_Fruit_Veg_Table()
        {
            this.Common_Fruit_Veg_Table1 = new HashSet<Common_Fruit_Veg_Table>();
            this.Common_Fruit_Veg_Table11 = new HashSet<Common_Fruit_Veg_Table>();
        }
    
        public int Fruit_Veg_Id { get; set; }
        public Nullable<int> Fruit_id { get; set; }
        public Nullable<int> Veg_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Common_Fruit_Veg_Table> Common_Fruit_Veg_Table1 { get; set; }
        public virtual Common_Fruit_Veg_Table Common_Fruit_Veg_Table2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Common_Fruit_Veg_Table> Common_Fruit_Veg_Table11 { get; set; }
        public virtual Common_Fruit_Veg_Table Common_Fruit_Veg_Table3 { get; set; }
    }
}
