//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lemon_Task.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Yogesh_Entity : DbContext
    {
        public Yogesh_Entity()
            : base("name=Yogesh_Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Common_Fruit_Veg_Table> Common_Fruit_Veg_Table { get; set; }
        public virtual DbSet<Fruits_Table> Fruits_Table { get; set; }
        public virtual DbSet<Vegetables_Table> Vegetables_Table { get; set; }
    }
}
