//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lemon_Task.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vegetables_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vegetables_Table()
        {
            this.Vegetables_Table1 = new HashSet<Vegetables_Table>();
        }
    
        public int Veg_id { get; set; }
        public string Veg_Name { get; set; }
        public Nullable<int> Fruit_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vegetables_Table> Vegetables_Table1 { get; set; }
        public virtual Vegetables_Table Vegetables_Table2 { get; set; }
    }
}
